name: Metrics Updater
on:
  schedule: [{cron: "30 20 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@v3
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ github.token }}

          user: GlaucousGlaucus
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_followup: yes
          plugin_followup_sections: repositories
          repositories: 200
          repositories_forks: no
